//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace Dev4ag.ISO11783.TimeLog
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DLV", Namespace="", AnonymousType=true)]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DLV", Namespace="")]
    public partial class DataLogValue
    {
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("A", DataType="hexBinary")]
        public byte[] ProcessDataDDI { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("B")]
        public string ProcessDataValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(4)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(DET|DET-)([0-9])+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("C")]
        public string DeviceElementIdRef { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ulong), "0", "262143")]
        [System.Xml.Serialization.XmlAttributeAttribute("D")]
        public ulong DataLogPGN { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataLogPGNSpecified { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(byte), "0", "63")]
        [System.Xml.Serialization.XmlAttributeAttribute("E")]
        public byte DataLogPGNStartBit { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataLogPGNStartBitSpecified { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(byte), "0", "63")]
        [System.Xml.Serialization.XmlAttributeAttribute("F")]
        public byte DataLogPGNStopBit { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataLogPGNStopBitSpecified { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PTN", Namespace="", AnonymousType=true)]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PTN", Namespace="")]
    public partial class Position
    {
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(object), "-90.0", "90.0")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("A")]
        public string PositionNorth { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(object), "-180.0", "180.0")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("B")]
        public string PositionEast { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(object), "-2147483648", "2147483647")]
        [System.Xml.Serialization.XmlAttributeAttribute("C")]
        public string PositionUp { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("D")]
        public string PositionStatus { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(object), "0.0", "99.9")]
        [System.Xml.Serialization.XmlAttributeAttribute("E")]
        public string PDOP { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(object), "0.0", "99.9")]
        [System.Xml.Serialization.XmlAttributeAttribute("F")]
        public string HDOP { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(object), "0", "254")]
        [System.Xml.Serialization.XmlAttributeAttribute("G")]
        public string NumberOfSatellites { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(object), "0", "4294967294")]
        [System.Xml.Serialization.XmlAttributeAttribute("H")]
        public string GpsUtcTime { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(object), "0", "65534")]
        [System.Xml.Serialization.XmlAttributeAttribute("I")]
        public string GpsUtcDate { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIM", Namespace="", AnonymousType=true)]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TIM", Namespace="")]
    public partial class Time
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Position> _position;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PTN")]
        public System.Collections.ObjectModel.Collection<Position> Position
        {
            get
            {
                return _position;
            }
            private set
            {
                _position = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PositionSpecified
        {
            get
            {
                return (this.Position.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public Time()
        {
            this._position = new System.Collections.ObjectModel.Collection<Position>();
            this._dataLogValue = new System.Collections.ObjectModel.Collection<DataLogValue>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DataLogValue> _dataLogValue;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DLV")]
        public System.Collections.ObjectModel.Collection<DataLogValue> DataLogValue
        {
            get
            {
                return _dataLogValue;
            }
            private set
            {
                _dataLogValue = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataLogValueSpecified
        {
            get
            {
                return (this.DataLogValue.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(0)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("A")]
        public string Start { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("D")]
        public Type Type { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TimeD", Namespace="", AnonymousType=true)]
    public enum Type
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Effective,
    }
}
