name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  buildLinux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x','6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl1.1 || sudo apt-get install -y libssl1.0.2  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Linux
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  buildWindows:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x','6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Windows
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  buildMac:

    runs-on: macos-12
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x','6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Mac
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal